name: "pupipa"

services:
  backend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
    ports:
      - "${PORT:-3001}:${PORT:-3001}"

  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
